### ISSUE TITLE
Tab Mix Plus breaks Noise Control

### ISSUE THREAD

**Issue by Caspy7** [darktrojan/noise-control#10]
I posted a link to Noise Control on reddit (so you may find an uptick in users).

At least two users are reporting that Tab Mix Plus breaks Noise Control:
http://www.reddit.com/r/firefox/comments/30zm0v/the_noise_control_addon_adds_pertab_audio/cpxl64x

**Comment by darktrojan** [comment]
Thanks for posting that @Caspy7. I'm not really surprised there's problems with TMP, but I haven't had a chance to deal with them.

**Comment by darktrojan** [comment]
I really hate Tab Mix Plus.

**Comment by blackwind** [comment]
Not fixed. Instead of showing an icon, my tabs now become 155px tall. Also, note that <a href="https://addons.mozilla.org/en-US/firefox/addon/tab-utilities-fixed/">Tab Utilities Fixed</a> has issues as well, as noted in the Reddit comment thread.

**Comment by darktrojan** [comment]
@blackwind have you restarted Firefox or increased the version number of the add-on since the changes?

**Comment by FatOrangutan** [comment]
For me, the tab bar only becomes 155px tall momentarily, it then goes back to its normal size and the volume icon shows up. This seems to happen only once (the first time) in every Firefox session.

**Comment by darktrojan** [comment]
@FatOrangutan That's a side effect of #8 I hadn't expected. I'll fix it.

**Comment by blackwind** [comment]
Had trouble with v9, but v10 is working.
