### ISSUE TITLE
Click to mute shouldn't switch to tab

### ISSUE THREAD

**Issue by blackwind** [darktrojan/noise-control#11]
In Chrome, when an inactive tab's noise indicator is clicked, focus remains on the currently selected tab. I believe this implementation makes more sense and would like to see it in Noise Control.

**Comment by darktrojan** [comment]
Yeah. Been meaning to fix that.

**Comment by jerone** [comment]
:+1:

**Comment by jerone** [comment]
Confirmed :+1: 

With https://github.com/darktrojan/noise-control/issues/15 not implemented (yet :smile: ) clicking the 'has active plugins` icon doesn't do anything; no mute, no tab switching. Just thinking that switching tabs with that icon only does make sense...

**Comment by blackwind** [comment]
I strongly suggest you begin testing with Classic Theme Restorer, Tab Mix Plus, and Tab Utilities Fixed, three of the most widely used add-ons. On my end with CTR and TMP, not only does it still switch tabs, I can't click to mute at all anymore.

**Comment by darktrojan** [comment]
While I'd love to support all those add-ons, my time isn't free. I'll make sure things are working for the vast majority of users. If you don't want to put up with the occasional bug like this (by all means report them), I strongly suggest you start paying my bills.
