### ISSUE TITLE
The icon does not appears in some HTML5 cases

### ISSUE THREAD

**Issue by timendum** [darktrojan/noise-control#12]
If the `audio` element element is not attached to the page document, the addon can't find the element so the icon is not produces.
[KhanAcademy](https://www.khanacademy.org/computing/computer-programming/programming/good-practices/p/readable-code#) for example use https://github.com/scottschiller/SoundManager2.

I've not found any solution :(

**Comment by darktrojan** [comment]
This is the same as #9.
