### ISSUE TITLE
Tab close buttons don't change color between foreground and background tabs

### ISSUE THREAD

**Issue by Gotolei** [darktrojan/noise-control#13]
Linux, Firefox 37.0, addon v10

Suspecting to be side effect of #8.

On any page where either the flash plugin is active or asking to be activated, the close button is changed to one color and then it stays that color.

My setup has the foreground tab on a light background, and background tabs with a dark background:
http://a.pomf.se/xfiprg.webm

In the screenshot, all the github tabs are asking to run flash and the youtube tab is in the process of running flash.
The reddit tabs are the only ones that display the close button correctly.

Possibly worth noting: Firefox appears to style the background tabs using  -moz-appearance: menu  which controls both the background and text colors.
[Relevant part of the linux browser.css](http://pastebin.com/a08nsZBW)

**Comment by darktrojan** [comment]
It looks as if the `selected` attribute isn't being changed on the close button. Which is weird because there is code that explicitly does it. Also it works fine on my Linux.

Have you got any other add-on that might be doing something with/to tabs?

**Comment by Gotolei** [comment]
Tab Mix Plus, I suppose. I'll try it in a fresh profile and report back.

**Comment by darktrojan** [comment]
Ah, I've just made a change that should fix that then. It'll be in the next version, whenever that is.

**Comment by Gotolei** [comment]
Fresh profile worked as intended. So yeah, definitely a compat issue with something.

**Comment by darktrojan** [comment]
Went ahead and released it since I have no other changes planned for now.

https://addons.mozilla.org/en-US/firefox/addon/noise-control/versions/11

**Comment by Gotolei** [comment]
Update fixed the problem, thanks :)
