### ISSUE TITLE
Add support for object AudioContext.

### ISSUE THREAD

**Issue by look997** [darktrojan/noise-control#14]
Add support for object AudioContext AudioNode?
Not work in https://github.com/katspaugh/wavesurfer.js

**Comment by darktrojan** [comment]
I think I'll need to fix #9 for this to happen. That might be some time, unfortunately.

**Comment by darktrojan** [comment]
I'm going to close this in favour of #9, since it is the same bug. Oddly the website seems to always have an audio channel open unless the track is muted, but I think that it's not my problem.
