### ISSUE TITLE
Icon on pinned tabs

### ISSUE THREAD

**Issue by jerone** [darktrojan/noise-control#16]
Aldo pinned tabs make room for the icon, I could be better aligned...
![Pinned tabs icon](https://cloud.githubusercontent.com/assets/55841/6993781/3d58337a-db00-11e4-80f4-6722568af3f5.png)

***

Firefox 38.0 beta 1 `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
Default theme

**Comment by darktrojan** [comment]
I'm sure that used to work properly :-/

**Comment by darktrojan** [comment]
Oh goody, the layout of the tab changed in Firefox 38. So there's another thing I have to check every time I make changes.

**Comment by jerone** [comment]
Confirmed :+1:
