### ISSUE TITLE
Icon color is tied to tab name's color

### ISSUE THREAD

**Issue by Zebouski** [darktrojan/noise-control#19]
![Image](http://i.imgur.com/BKY9Tym.png)
The top third is an inactive tab, all is well.
The middle third is a hovered-upon tab, the music icon turns blue while the X stays gray
The bottom third is the active tab, same deal, the blue vs gray icons look silly.

Can it be changed so that the icon is tied to whatever color the X is, and not whatever color the title text is?

[Here's the userstyle I am demonstrating with.](https://userstyles.org/styles/94667/selected-tab-blue-font-color-for-ft-deepdark)

**Comment by darktrojan** [comment]
I agree icon colour should be and one day will be an option. In the mean time you could use Stylish to set it, here's the CSS you'd need:

```
svg[anonid="noise-indicator"] > use {
	fill: #123456;
}
```

**Comment by darktrojan** [comment]
I've just landed changes that will allow for changing the colour of the indicator. They'll be in the next version.
