### ISSUE TITLE
Decide whether to continue now Nightly has this feature

### ISSUE THREAD

**Issue by darktrojan** [darktrojan/noise-control#24]
Nightly has a noisy tab feature now, so I need to decide whether to do any more development, or to abandon Noise Control.

**Comment by jerone** [comment]
Is there any difference between nightly and this addon?

**Comment by darktrojan** [comment]
In essence, no, but they do things differently because the Firefox developers can just change the browser to suit their needs. There is potential to add enhancements to the built-in version though, like the noisy tabs sidebar I've been working on.

**Comment by look997** [comment]
I propose to add support for native solutions and add option:
mute if tab is in the background.

Actually, it would be worth it to add natively in Firefox.

**Comment by darktrojan** [comment]
Okay, I've decided. I will be abandoning Noise Control when the built-in feature reaches Firefox release.
