### ISSUE TITLE
Some soundless videos display an audio notification

### ISSUE THREAD

**Issue by Caspy7** [darktrojan/noise-control#6]
Currently running version 7.
See the following pages which trigger the audio notification with no sound.
http://mashable.com/2015/02/23/neil-patrick-harris-best-oscars-moments/
https://www.ghostery.com/en/

I don't know if it's connected, but curiously, inline GIFVs on Reddit do *not* trigger the notification. However, using the Imagus addon to preview GIFVs does trigger the audio notification icon (on reddit and imgur).

**Comment by darktrojan** [comment]
I'm going to close this. It should work now, but the Ghostery page still shows an icon, because according to Firefox, that video has audio.
