### ISSUE TITLE
Incompatible with Soundcloud

### ISSUE THREAD

**Issue by SW1FT** [darktrojan/noise-control#7]
As the title says. Also, Soundcloud uses a mix of HTML5 and Flash in their player, so sometimes it will use Flash and some other times it will use HTML5.

**Comment by darktrojan** [comment]
Works for me. I get the question mark icon because of the Flash content.

Is the problem you're reporting that the icon doesn't go away when SoundCloud is paused? Because that's definitely a problem, but I can't really do anything about it.

**Comment by nkestrel** [comment]
Disabling Flash forces the SoundCloud HTML5 player which does not show any Noise Control icon.

**Comment by darktrojan** [comment]
Okay, I know what's up. Could be a real nasty thing to fix though. There's an easy way but it's broken too.

**Comment by SW1FT** [comment]
Sometimes it shows the question mark icon, sometimes it doesn't, it's pretty weird.

**Comment by darktrojan** [comment]
See #9 for any further info on this bug.
