### ISSUE TITLE
Icon contrast against different backgrounds

### ISSUE THREAD

**Issue by nkestrel** [darktrojan/noise-control#8]
I've noticed problems with the icon contrast in themes (eg FTDeepDark) as well as Tree Style Tabs which make it hard to see. Instead of using an icon it could be using a unicode symbol which allows it to change color according to the "currentcolor" css value (used for text) which makes it more robust with different themes and addons. 

Example:

    .tab-content::after {
      content: "🔊"; /*🔈 🔊 🔇*/
      color: currentcolor;
      font-family: Segoe UI Symbol;  /*needed to control symbol color*/
      font-size: medium;
      display: -moz-box;
    }

**Comment by darktrojan** [comment]
I haven't had a chance to figure out themes yet. What you've suggested definitely has some potential.

**Comment by SW1FT** [comment]
Can you make an option for people to choose the color of their icon?

**Comment by blackwind** [comment]
On my system, at least, the currentcolor solution is inadequate:

http://i.imgur.com/eDHjAmT.png

It selects black for inactive tabs, which, with my monitor's brightness as low as it is, makes the icon almost completely indistinguishable from the tab.

**Comment by nkestrel** [comment]
It should be the same color as the tab text if it is working properly. Initially it didn't work for me either but a restart fixed it.

I noticed the icon has changed from an image to an svg element rather than text. One of the benefits of text is it can have a shadow/glow applied to it according to the theme, a lot of themes rely on this for making their tab text readable against varied backgrounds. Consequently for some themes the icon doesn't stand out as much as the tab text. 

![](http://i.imgur.com/MWuvZAw.png)

Also note that the close icon does not adopt any theme color but has an outer glow which helps it stand out.

**Comment by blackwind** [comment]
It should be -- you're absolutely right -- but it isn't. For me, restarting had no effect.

**Comment by blackwind** [comment]
I've coordinated with the developer of Classic Theme Restorer to resolve my issue. If anyone else is experiencing it, the fix will be included in v1.3.1.
